spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    change-log: classpath:db/db.changelog.yaml
    enabled: true
  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    vendor: ${SPRING_MAIL_VENDOR}
    templates:
      - type: ACTIVATION
        defaultSubject: "Welcome to IWantToVisit.org!"
        template: "activation.ftlh"
        properties:
          mainLink: ${MAIL_MAIN_LINK}
          mainDomainName: ${MAIL_DOMAIN}
          link: ${MAIL_ACTIVATION_LINK}
      - type: PASSWORD_RESET
        defaultSubject: "Password resetting on IWantToVisit.org"
        template: "restore.ftlh"
        properties:
          mainLink: ${MAIL_MAIN_LINK}
          mainDomainName: ${MAIL_DOMAIN}
          link: ${MAIL_RESTORE_LINK}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        generate_statistics: false
        show_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

server:
  tomcat:
    relaxed-query-chars: "[,]"
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}
  access: ${JWT_ACCESS_DURATION}
  refresh: ${JWT_REFRESH_DURATION}
  activation: ${JWT_ACTIVATION_DURATION}
  reset: ${JWT_RESET_DURATION}