spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    change-log: classpath:db/db.changelog.yaml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        generate_statistics: false
        show_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

server:
  tomcat:
    relaxed-query-chars: "[,]"
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

logging:
  level:
    root: INFO